### ISSUE TITLE
attachment_minio .This addon should give credits to camptocamp

### ISSUE THREAD

**Issue by lmignon** [hibou-io/hibou-odoo-suite#11]
It appears that this addon is a derivative work of attachment_s3 from camptocamp https://github.com/camptocamp/odoo-cloud-platform/blob/13.0/attachment_s3. It's stange to see that C2C is not mentioned into the author list and credits not preserved into file headers....

**Comment by jaredkipe** [comment]
At best it is a rewrite as it uses a completely separate API implementation and has different requirements and concerns for setup/implementation.

Given that they are new files they don't "preserve" headers, what would be your suggestion for "inspired by" inclusion?

**Comment by lmignon** [comment]
it's a derivative work and a diff between the two addons highlight a lot of similarities. You should at least preserve the initial copyright ir_attachment.py file as you already did with s3uri.py. Copyright are cumulative, therefore you can also add yours into the ir_attachment for all your changes.

**Comment by jaredkipe** [comment]
Thanks, I will be sure to start adding myself onto copyright headers on the OCA modules I migrate.

**Comment by lmignon** [comment]
@jaredkipe For OCA, you can add you into the list of contributors of any addons....
