### ISSUE TITLE
REQUEST 12.0 VERSION - HR-FLORIDA

### ISSUE THREAD

**Issue by xAlphaOmega** [hibou-io/hibou-odoo-suite#8]
I would like to Make a request of payroll module for Florida that works with 12.0 please.

**Comment by jaredkipe** [comment]
Available right now in `mig/12.0/us_payroll`, docker image registry.gitlab.com/hibou-io/hibou-odoo/suite:mig-12-0-us-payroll
https://gitlab.com/hibou-io/hibou-odoo/suite/issues/31

**Comment by xAlphaOmega** [comment]
I am so grateful, thank you very much.
